/*
 * FlightDelayPass API
 * FlightDelayPass application
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.flight_delay_pass_reference.api;

import com.mastercard.developer.flight_delay_pass_reference.ApiException;
import com.mastercard.developer.flight_delay_pass_reference.model.RegistrionResponse;
import com.mastercard.developer.flight_delay_pass_reference.model.UserRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FlightDelayControllerApi
 */
@Ignore
public class FlightDelayControllerApiTest {

    private final FlightDelayControllerApi api = new FlightDelayControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postRegistrationTest() throws ApiException {
        String xOpenapiClientid = null;
        UserRequest userRequest = null;
        RegistrionResponse response = api.postRegistration(xOpenapiClientid, userRequest);

        // TODO: test validations
    }
    
}
