/*
 * FlightDelayPass API
 * FlightDelayPass application
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.flight_delay_pass_reference.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.developer.flight_delay_pass_reference.model.Account;
import com.mastercard.developer.flight_delay_pass_reference.model.AdditionalPassengerDetails;
import com.mastercard.developer.flight_delay_pass_reference.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UserRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-22T14:30:47.482-06:00[America/Chicago]")
public class UserRequest {
  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private User user = null;

  public static final String SERIALIZED_NAME_ACCOUNTS = "accounts";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS)
  private List<Account> accounts = new ArrayList<Account>();

  public static final String SERIALIZED_NAME_PROPOSITION = "proposition";
  @SerializedName(SERIALIZED_NAME_PROPOSITION)
  private String proposition;

  public static final String SERIALIZED_NAME_FLIGHT_NUMBER = "flightNumber";
  @SerializedName(SERIALIZED_NAME_FLIGHT_NUMBER)
  private String flightNumber;

  public static final String SERIALIZED_NAME_DEPARTURE_AIRPORT_CODE = "departureAirportCode";
  @SerializedName(SERIALIZED_NAME_DEPARTURE_AIRPORT_CODE)
  private String departureAirportCode;

  public static final String SERIALIZED_NAME_DEPARTURE_DATE = "departureDate";
  @SerializedName(SERIALIZED_NAME_DEPARTURE_DATE)
  private String departureDate;

  public static final String SERIALIZED_NAME_ARRIVAL_AIRPORT_CODE = "arrivalAirportCode";
  @SerializedName(SERIALIZED_NAME_ARRIVAL_AIRPORT_CODE)
  private String arrivalAirportCode;

  public static final String SERIALIZED_NAME_ADDITIONAL_PASSENGER_DETAILS = "additionalPassengerDetails";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_PASSENGER_DETAILS)
  private List<AdditionalPassengerDetails> additionalPassengerDetails = null;

  public static final String SERIALIZED_NAME_FIRST_P_A_N = "firstPAN";
  @SerializedName(SERIALIZED_NAME_FIRST_P_A_N)
  private String firstPAN;

  public UserRequest user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public UserRequest accounts(List<Account> accounts) {
    this.accounts = accounts;
    return this;
  }

  public UserRequest addAccountsItem(Account accountsItem) {
    this.accounts.add(accountsItem);
    return this;
  }

   /**
   * Get accounts
   * @return accounts
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Account> getAccounts() {
    return accounts;
  }

  public void setAccounts(List<Account> accounts) {
    this.accounts = accounts;
  }

  public UserRequest proposition(String proposition) {
    this.proposition = proposition;
    return this;
  }

   /**
   * Get proposition
   * @return proposition
  **/
  @ApiModelProperty(value = "")
  public String getProposition() {
    return proposition;
  }

  public void setProposition(String proposition) {
    this.proposition = proposition;
  }

  public UserRequest flightNumber(String flightNumber) {
    this.flightNumber = flightNumber;
    return this;
  }

   /**
   * Get flightNumber
   * @return flightNumber
  **/
  @ApiModelProperty(value = "")
  public String getFlightNumber() {
    return flightNumber;
  }

  public void setFlightNumber(String flightNumber) {
    this.flightNumber = flightNumber;
  }

  public UserRequest departureAirportCode(String departureAirportCode) {
    this.departureAirportCode = departureAirportCode;
    return this;
  }

   /**
   * Get departureAirportCode
   * @return departureAirportCode
  **/
  @ApiModelProperty(value = "")
  public String getDepartureAirportCode() {
    return departureAirportCode;
  }

  public void setDepartureAirportCode(String departureAirportCode) {
    this.departureAirportCode = departureAirportCode;
  }

  public UserRequest departureDate(String departureDate) {
    this.departureDate = departureDate;
    return this;
  }

   /**
   * Get departureDate
   * @return departureDate
  **/
  @ApiModelProperty(value = "")
  public String getDepartureDate() {
    return departureDate;
  }

  public void setDepartureDate(String departureDate) {
    this.departureDate = departureDate;
  }

  public UserRequest arrivalAirportCode(String arrivalAirportCode) {
    this.arrivalAirportCode = arrivalAirportCode;
    return this;
  }

   /**
   * Get arrivalAirportCode
   * @return arrivalAirportCode
  **/
  @ApiModelProperty(value = "")
  public String getArrivalAirportCode() {
    return arrivalAirportCode;
  }

  public void setArrivalAirportCode(String arrivalAirportCode) {
    this.arrivalAirportCode = arrivalAirportCode;
  }

  public UserRequest additionalPassengerDetails(List<AdditionalPassengerDetails> additionalPassengerDetails) {
    this.additionalPassengerDetails = additionalPassengerDetails;
    return this;
  }

  public UserRequest addAdditionalPassengerDetailsItem(AdditionalPassengerDetails additionalPassengerDetailsItem) {
    if (this.additionalPassengerDetails == null) {
      this.additionalPassengerDetails = new ArrayList<AdditionalPassengerDetails>();
    }
    this.additionalPassengerDetails.add(additionalPassengerDetailsItem);
    return this;
  }

   /**
   * Get additionalPassengerDetails
   * @return additionalPassengerDetails
  **/
  @ApiModelProperty(value = "")
  public List<AdditionalPassengerDetails> getAdditionalPassengerDetails() {
    return additionalPassengerDetails;
  }

  public void setAdditionalPassengerDetails(List<AdditionalPassengerDetails> additionalPassengerDetails) {
    this.additionalPassengerDetails = additionalPassengerDetails;
  }

  public UserRequest firstPAN(String firstPAN) {
    this.firstPAN = firstPAN;
    return this;
  }

   /**
   * Get firstPAN
   * @return firstPAN
  **/
  @ApiModelProperty(value = "")
  public String getFirstPAN() {
    return firstPAN;
  }

  public void setFirstPAN(String firstPAN) {
    this.firstPAN = firstPAN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRequest userRequest = (UserRequest) o;
    return Objects.equals(this.user, userRequest.user) &&
        Objects.equals(this.accounts, userRequest.accounts) &&
        Objects.equals(this.proposition, userRequest.proposition) &&
        Objects.equals(this.flightNumber, userRequest.flightNumber) &&
        Objects.equals(this.departureAirportCode, userRequest.departureAirportCode) &&
        Objects.equals(this.departureDate, userRequest.departureDate) &&
        Objects.equals(this.arrivalAirportCode, userRequest.arrivalAirportCode) &&
        Objects.equals(this.additionalPassengerDetails, userRequest.additionalPassengerDetails) &&
        Objects.equals(this.firstPAN, userRequest.firstPAN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, accounts, proposition, flightNumber, departureAirportCode, departureDate, arrivalAirportCode, additionalPassengerDetails, firstPAN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRequest {\n");
    
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("    proposition: ").append(toIndentedString(proposition)).append("\n");
    sb.append("    flightNumber: ").append(toIndentedString(flightNumber)).append("\n");
    sb.append("    departureAirportCode: ").append(toIndentedString(departureAirportCode)).append("\n");
    sb.append("    departureDate: ").append(toIndentedString(departureDate)).append("\n");
    sb.append("    arrivalAirportCode: ").append(toIndentedString(arrivalAirportCode)).append("\n");
    sb.append("    additionalPassengerDetails: ").append(toIndentedString(additionalPassengerDetails)).append("\n");
    sb.append("    firstPAN: ").append(toIndentedString(firstPAN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

