/*
 * FlightDelayPass API
 * FlightDelayPass application
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.flight_delay_pass_reference.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
